FROM alpine:latest

RUN apk update && \
    apk add --no-cache nginx

RUN mkdir -p /run/nginx /var/lib/nginx/html /usr/share/nginx/html /var/www/localhost/htdocs && \
    echo "<h1>Application Deployed via Terraform IaC!</h1>" > /var/lib/nginx/html/index.html && \
    echo "<h1>Application Deployed via Terraform IaC!</h1>" > /usr/share/nginx/html/index.html && \
    echo "<h1>Application Deployed via Terraform IaC!</h1>" > /var/www/localhost/htdocs/index.html

RUN printf 'server {\n    listen 80;\n    server_name _;\n    root /var/www/localhost/htdocs;\n    index index.html;\n\n    location / {\n        try_files $uri $uri/ =404;\n    }\n}\n' > /etc/nginx/http.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]